module.exports = {
	INVALID_DATA: field => `DATA NOT SEND OR INVALID: '${field}'`,
	INVALID_DATA_USER: 'Usuario o contraseña incorrectos',
	INVALID_INSCRIPTION: 'Tu usuario no está habilitado para acceder a la Autogestión',
	PENDING_SURVEY: 'Tu usuario posee encuestas obligatorias por responder, serás redireccionado',
	INACTIVE_EMAIL: 'Tu email se encuentra inactivo, serás redireccionado',
	PENDING_STUDENT_REGULATION: 'Tienes pendiente el reglamento de alumnos, serás redireccionado',
	PASSWORD_EXPIRED: 'Tu contraseña está vencida, serás redireccionado',
	NO_AREAS: field => `No se encontraron áreas con el parámetro: '${field}'`,
	NO_COUNTRIES: 'No se encontraron países',
	NO_PROVINCE_FOUNDED: field => `No se encontraron provincias con el id país: '${field}'`,
	NO_LOCALITY_FOUNDED: field => `No se encontraron localidades con el id provincia: '${field}'`,
	NO_NEIGHBORHOOD_FOUNDED: field => `No se encontraron barrios con el id localidad: '${field}'`,
	NO_CAREERS_FOUNDED: field => `No se encontraron carreras para el usuario con el Dni: ${field}`,
	ADDRESS_TYPE_ALREADY_EXISTS: 'El tipo de domicilio ya existe',
	PHONE_TYPE_ALREADY_EXISTS: 'El tipo de teléfono ya existe',
	STUDENT_NOT_EXISTS: dni => `No se encontro un estudiante con el DNI: ${dni}`,
	PHONE_NOT_FOUNT: phone => `No se encontro el telefono: ${phone} asociado al estudiante`,
	EMAIL_NOT_FOUNT: 'Debe cargar un e-mail para realizar la solicitud',
	NO_INTERVIEW_PENDING: 'No se encontraron encuestas pendientes',
	NO_DATES_AVAILABLE: 'En estos momentos no hay turnos disponibles. Por favor intenta en los próximos días.',
	DATE_NO_LONGER_AVAILABLE: 'El turno seleccionado ya no se encuentra disponible.',
	NO_DOCUMENTATION_OWED: 'No se adeuda documentación.',
	NO_ABSENSE_REGISTERED: 'No se registran inasistencias para el alumno.',
	HAS_NO_CAREERS_ASSIGNED: 'No se encuentra inscripto a ninguna carrera',
	REDIRECT_TO_PERSONAL_INFORMATION: 'Posee datos pendientes de completar, será redireccionado a datos personales.',
	INVALID_SEMESTER_INSCRIPTION_HAS_SCOLARSHIP: `UD. POSEE BECA PARA LA PREINSCRIPCIÓN REALIZADA EN EL SEMESTRE EN CURSO.
	* Para realizar cambios en la PreInscripción dirigirse a la Bedelía de la correspondiente modalidad.`,
	PERIOD_INSCRIPTION_CUATRIMESTRAL_INHABILITATED: 'No está habilitado el período de Inscripción Cuatrimestral',
	PERIOD_MODIFIE_INSCRIPTION_INHABILITATED: 'No está habilitado el período para gestionar los cambios de Inscripción',
	PENDING_DOCUMENTATION: 'Para poder realizar el trámite de Inscripción se debe completar la Documentación Adeudada (Indicada en Color Rojo)',
	STUDENT_INHABILITATION: 'El alumno presenta INHABILITACION',
	NO_SUBJECTS_ENROLLED_FOUNDED: 'Sobre estas asignaturas ya se realizó una preinscripción. Pasar por caja para finalizar el proceso de inscripción.',
	PROCESS_ALREADY_IN_COURSE: `ATENCIÓN!! Ya posee un trámite iniciado para cambiar la modalidad.
	Secretaría Académica se comunicará a la brevedad.`,
	CAREER_NOT_EXISTS: id => `No se encontró una carrera con el ID: ${id}`,
	NO_MID_TERM_EXAMS_FOUNDED: 'Aún no hay parciales cargados',
	NO_CIES_EXAMS_FOUNDED: 'No se encontraron exámenes CIES',
	DOWNLOAD_INHABILITATED: 'En estos momentos no se puede realizar la descarga del examen.',
	NO_BALANCE: 'No posee saldo',
	ALREADY_SUBJECT_INSCRIPTION: 'No se puede rendir más de un (1) examen por día'
};
